import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import AcampsLogo from "@/public/acamps.webp";
import Image from "next/image";
import HeaderMenu from "@/components/menu";
import Link from "next/link";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={quicksand.className}>
        <header className="w-full flex p-2 md-p-1 gap-10 bg-zinc-100">
          <Link href="/">
            <Image src={AcampsLogo} alt="Acamps" />
          </Link>
          <HeaderMenu />
        </header>
        {children}
      </body>
    </html>
  );
}
